### PR TITLE
adding the pyproject.toml and setup.cfg files. fix #335 

### LINKED ISSUE #335: Packaging Niffler with pip
This is slightly tricky since Niffler is not just Python.

Among the modules, the below are in Python: 
* cold-extraction
* dicom-anonymization
* meta-extraction
* nifti-extraction
* png-extraction
* rta-extraction
* suvpar

Although the above could be packaged with pip following [1], there are complex dependencies such as DCM4CHE as storescp for cold-extraction and meta-extraction, mongo for meta-extraction, and gdcm for png-extraction. Additional care must be taken on initiatives on packaging Niffler as an installable configuration to ensure this is complete.

[1] https://packaging.python.org/en/latest/tutorials/packaging-projects/

### PR DESCRIPTION
**Pull request by Shazam213**
Hello @pradeeban ,
 I tried packaging niffler with pip. I have created the required pyproject.toml and setup.cfg files required to generate the .whl file. The .whl file is present in the /dist folder. Could you please review the .whl file by running the command: `pip install Niffler-0.9.3-py3-none-any.whl`  in the folder where .whl is present. If the required installations of package is correct then i would also add the pip package to https://pypi.org/ from where anyone could install Niffler packages just by using the commands pip install Niffler.
 fix #335

### CODE REVIEW

**Comment by pradeeban** [comment]
Hi and welcome @Shazam213. Thanks for your contributions. This is great.

**Comment by pradeeban** [comment]
@Shazam213 I have merged it since your commits won't hurt the execution. But we have to wait on sending to pypi until we review the implications from that. The first issue I see is, how it would interact with other dependencies (including with projects developed in Java, such as DCM4CHE and databases such as Mongo that is used by the real-time execution).

I believe we can hold on from committing to Pypi. cc'd @anbhimi.

**Comment by anbhimi** [comment]
@Shazam213 The submitted code files and the corresponding wheel file were well made covering all the python dependencies. But the PR did not account for some trivial non-python packages such as GDCM, JDK, Maven, and DCM4CHE. Modules like cold extraction cannot function without these dependencies. Please review install.sh along with the requirements-dev.txt file to find all the required packages. 

Though pymongo is installed through the wheel file, MongoDB should also be explicitly installed. Non-trivial packages such as Mail were also ignored in the submitted files.

**Comment by Shazam213** [comment]
Sure, I had included all of the requirements-dev files in the setup.cfg file, but I will revisit install.sh.
Whereas for MongoDB and other non-trivial packages, as well as non-python packages, I'm working on how to add those dependencies to the setup.cfg file, and also looking for methods to link the installs of such dependencies?

**Comment by Shazam213** [comment]
hii @pradeeban @anbhimi , i tried adding the Niffler git repo as direct URL dependency in the setup.cfg file by referring to:
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#direct-url-dependencies. I am not sure whether it would completely solve our problem though. Would you please let me know whether this method would work or not and if it would work then i would also try and add the remaining non trivial dependencies by there git repos.

**Comment by pradeeban** [comment]
It is tricky with all the manual configurations we do (which you can check from the README). Your PR is a good start. Let's hold on to this until we have a clearer idea of how to handle the complex dependencies and automatically configure those at installation.

Please do not commit to https://pypi.org/, though. It will likely confuse the users at this point.

**Pull request merged**
